import {
    siHtml5,
    siBootstrap,
    siJavascript,
    siPhp,
    siMysql,
    siReact,
    siTailwindcss,
    siExpress,
    siNodedotjs,
    siMongodb,
    siNextdotjs,
    siSocketdotio,
    siWebflow,
  } from "simple-icons";

export const technologies = [
    { icon: siHtml5, name: "HTML", hex: siHtml5.hex },
    { icon: siBootstrap, name: "Bootstrap", hex: siBootstrap.hex },
    { icon: siJavascript, name: "JavaScript", hex: siJavascript.hex },
    { icon: siPhp, name: "PHP", hex: siPhp.hex },
    { icon: siMysql, name: "MySQL", hex: siMysql.hex },
    { icon: siTailwindcss, name: "TailwindCSS", hex: siTailwindcss.hex },
    { icon: siReact, name: "ReactJS", hex: siReact.hex },
    { icon: siNodedotjs, name: "NodeJS", hex: siNodedotjs.hex },
    { icon: siExpress, name: "ExpressJS", hex: "ffffff" },
    { icon: siMongodb, name: "MongoDB", hex: siMongodb.hex },
    { icon: siSocketdotio, name: "Socket.io", hex: siSocketdotio.hex },
    { icon: siNextdotjs, name: "NextJS", hex: siNextdotjs.hex },
    { icon: siWebflow, name: "Webflow", hex: siWebflow.hex },
  ];